### ISSUE TITLE
Checking for isComponent vs isApp fails in super dev mode

### ISSUE THREAD

**Issue by hellofornow** [Axellience/vue-gwt#1]
https://github.com/Axellience/vue-gwt/blob/master/src/main/resources/com/axellience/vuegwt/client/jsnative/VueGwtTools.js#L24
is the culprit.
Checking for property '$$el' explicitly fails as super-dev appends the build increment (for example '$$el_0_g$')
![image](https://cloud.githubusercontent.com/assets/3720413/21626760/43fa29ae-d1d0-11e6-8b27-ade88aa0c8df.png)

Suggestion would be to pass isComponent in from GWT.

**Comment by adrienbaron** [comment]
Thanks for the report 👍 

This error occurs probably because you haven't put the JsInterop flag in your superdevmode:
-generateJsInteropExports

I'm working on an update to make the API easier (by dropping VueApp and keeping only VueComponent). I'll also improve the documentation for this kind of issues.
Should be out today.
