### ISSUE TITLE
better support for others libraries management tools

### ISSUE THREAD

**Issue by rlagoue** [Axellience/vue-gwt#28]
the packaging value for the module vue-gwt-processors is "jar" (https://search.maven.org/remotecontent?filepath=com/axellience/vue-gwt-processors/1.0-beta-6/vue-gwt-processors-1.0-beta-6.pom)

Unfortunately the value is "gwt-lib" for the modules vue-gwt and vue-gwt-core (https://search.maven.org/remotecontent?filepath=com/axellience/vue-gwt/1.0-beta-6/vue-gwt-1.0-beta-6.pom,  https://search.maven.org/remotecontent?filepath=com/axellience/vue-gwt-core/1.0-beta-6/vue-gwt-core-1.0-beta-6.pom). It causes resolve tasks to fail when working with apache ivy. 

It would be nice to rename it to "jar" too

**Comment by rlagoue** [comment]
hey @adrienbaron 

can I fix it by myself, since I am waiting for this to start with vue-gwt?

Best regards

**Comment by adrienbaron** [comment]
@rlagoue Sure you can try to clone our repo locally on the master fix it and do `mvn clean install`.
The actual fix should be done on the develop for Beta 7, but the documentation for Beta 7 is not up yet so you should rather use Beta 6 for your project for now.
We are using trboyer GWT maven plugin (https://github.com/tbroyer/gwt-maven-plugin) so that's where the `gwt-lib` comes from. Just replacing by `jar` might break some things. You can ask on the Gitter also, maybe Colin or James will have an idea.

**Comment by rlagoue** [comment]
Ok I was supposing that the solution would be easy as just changing it. So I will continue to fight with Beta 6 usage. :-)

**Comment by adrienbaron** [comment]
Removing the gwt-lib would break the build with the tbroyer GWT maven plugin to my best knowledge.
So for now we have to keep it even it breaks compatibility with Apache Ivy.
So we won't fix for now, solution might be to look how to make Apache Ivy accept gwt-lib as it's fairly popular amongst modern GWT librairies.

**Comment by rlagoue** [comment]
ok, I hava found a away to declare it properly in the dependency, thank you
