### ISSUE TITLE
Support for new versions of Vue.js 

### ISSUE THREAD

**Issue by slavap** [Axellience/vue-gwt#6]
Current vue version is 2.5.2.
Is there any proper way how to configure vue-gwt to use newer version of vue, or it's supposed to be always hardcoded in vue-gwt? Then when to expect new release of vue-gwt based on 2.5.2 ? It would be nice to have vue dependency configurable, for example loaded manually in index.html

**Comment by adrienbaron** [comment]
We are working on beta-3 that will include the upgrade to 2.5.2 (the [commit](https://github.com/Axellience/vue-gwt/commit/613d22f3faec3ca69165494266d25fdf40ef847f) is actually already on develop)

For the fact that the version has to be hardcoded it's a little more complicated.
Vue GWT uses two parts of Vue.js, the template compiler and the runtime. Both are released at the same time as part of a new version of Vue.js.
The template compiler is used at GWT compiled time. It's loaded into Nashorn (the JS engine in the JVM) and used to compile the HTML templates of the components to a JS render function. So it can't be provided by the user of the library.
The runtime is used as it's name indicates at runtime and is injected by Vue GWT in your document when your app starts.

It's possible to provide your own runtime, in any version, if you wish to. For that you just get the `vue.runtime.min.js` from [Vue.js repo](https://github.com/vuejs/vue/tree/dev/dist). In your code you then call `VueGWT.initWithoutVueLib();` instead of `VueGWT.init();` to avoid injecting the runtime included in Vue GWT.
Depending on the change in the Vue template compiler, the runtime might not be compatible, and Vue doesn't intend to work with a difference of version between the template compiler and the runtime. But if the template compiler hasn't changed between versions then it will work. Sadly it changed a lot in 2.5, so I'm not convinced for that update, but you can try.

Lastly, some new features of Vue.js require new Java declaration to work, for example in 2.5 the [new error handler](https://gist.github.com/yyx990803/9bdff05e5468a60ced06c29c39114c6b#error-handling-with-errorcaptured-hook) will require a new interface to implement in the Vue GWT.

**Comment by slavap** [comment]
Thank you for detail explanation. I’m absolutely ok with some reasonable waiting for update vue-gwt, just wanted to be sure that project will follow vue release cycle.

**Comment by adrienbaron** [comment]
@slavap I just saw that backward compatibility with previous compiler is actually ensured in Vue.js 🎉!
If you look at this [github issue](https://github.com/vuejs/vue/issues/6803), Evan You the creator of Vue.js ensure that template compiled in previous version should work in new ones.
So you should be able to swap the runtime for a more recent one if needed.

**Comment by adrienbaron** [comment]
Vue GWT has just been updated to Vue.js 2.5.5 on beta-3.
